### ISSUE TITLE
Generate an arbitrary file containing the latest version number

### ISSUE THREAD

**Issue by GeertJohan** [stack11/trek#14]
I use a package that has the db version number in it. When components such as API's and workers start, they validate whether the db is at that version, and otherwise exit.

The file with the version number in it looks like this:

```go
package dbversion

// LatestVersion is the latest version for the db migrations.
const LatestVersion = 43
```

It would be good if trek generates this. We could make trek 'aware' of Go and any other language. But it's probably better to add a simple templating feature:

In the trek.yaml:

```yaml
templates:
  - path: dbversion/version.go
    content: |
      package dbversion

       // LatestVersion is the latest version for the db migrations.
       const LatestVersion = {{.NewVersion}}
```

`{{.NewVersion}}` is the only variable available in the template. It is an unquoted number without zerofill.

Eventually, when `trek check` arrives, it could also validate that the target file is equal to what `trek generate` would generate.
